# Generated by Django 4.2.11 on 2024-05-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
    ]
