# Generated by Django 4.2.11 on 2024-05-05 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_event_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
